name: CD for FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Decode the Base64 private key and save it
      - name: Decode SSH Key
        run: echo "${{ secrets.SERVER_KEY }}" | base64 -d > /tmp/id_rsa
        shell: bash

      # Adjust permissions of the private key
      - name: Set SSH Key Permissions
        run: chmod 600 /tmp/id_rsa

      # Deploy to the server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key_path: /tmp/id_rsa
          port: 61001
          script: |
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker pull shams316/fastapi-app:ci-latest
            docker run -d --name fastapi-app -p 8000:8000 shams316/fastapi-app:ci-latest
