name: CD for FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: SSH into the server and deploy the application
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }} # Base64-encoded private key
          key_format: base64             # Decode Base64
          port: 61001
          script: |
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker pull shams316/fastapi-app:ci-latest
            docker run -d --name fastapi-app -p 8000:8000 shams316/fastapi-app:ci-latest
